export * from './input'
export * from './iAgree'
export * from './modal'
export * from './intro'
export * from './bgImage'
export * from './submitItem'
export * from './calendarLovey'
export * from './tabGlobalButton'